
--- Estas  querys tem a finalidade  de evidenciar a Transferencia de Outorgas 
--- Devido ser uma operação do cobilling , os registros com chamadas locais são desconsiderados. Somente chamdas LD são consideradas.
--- Devido o outorgas ser baseado no cobilling abaixo segue um esquema da divisão dos arquivos:


     --- Arquivos  TLM
	 
	       -- tipos: 
		           -- Universal ( Rejeitados, Ok e Erro )
				   -- Outorgas  ( Rejeitados , Ok e Erro )
				   -- Normal      ( Rejeitados, Ok e Erro )
		    
	 
	 
	 --- Arquivos  PMS 
	 
          -- tipos: 
		       --- Normal  ( Rejeitados , Ok e Erro )
			    
		  
		  
		        
 ----------------------------------------------------------------   Arquivos   PMS   --------------------------------------

 -- Os arquivos  PMS  não possuem as operadoras  ( 31,88,90 ) . 

SELECT *   FROM CHAMADA a 
WHERE DT_INICIO > TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS') AND DT_INICIO <  (SYSDATE -2)
 AND ( (SUBSTR(TP_TARIFACAO,0,4)='0300') OR (SUBSTR(TP_TARIFACAO,0,3)='LDI') 
 OR (SUBSTR (tp_tarifacao, 0, 5) = 'VC1FM')  OR (SUBSTR (tp_tarifacao, 0, 5) = 'VC1FF') 
 OR (SUBSTR (tp_tarifacao, 0, 6) = 'VC1FOI') OR  (SUBSTR(TP_TARIFACAO,0,3)='VCF') 
 OR (SUBSTR(TP_TARIFACAO,0,3)='VC3') OR (SUBSTR(TP_TARIFACAO,0,3)='VC2' 
 AND TO_NUMBER(NVL(CD_OPLD_B,'0')) NOT IN (88,89) ) ) AND SUBSTR(TRIM(MSISDN_B),0,1) <> 'A' 
 AND CD_OPLD NOT IN ('31', '88', '90')
---  total : 50




--------------------------------------------------------------   Arquivos  TLM     -----------------------------------------

--  Os arquivos TLM possuem as operadoras (CD_OPLD) igual  a   31, 88 e 90 )

-- Query para identificar um arquivo TLM 
SELECT COUNT (*)  FROM CHAMADA a 
WHERE DT_INICIO > TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS') AND DT_INICIO <  (SYSDATE -2)
 AND ( (SUBSTR(TP_TARIFACAO,0,4)='0300') OR (SUBSTR(TP_TARIFACAO,0,3)='LDI') 
 OR (SUBSTR (tp_tarifacao, 0, 5) = 'VC1FM')  OR (SUBSTR (tp_tarifacao, 0, 5) = 'VC1FF') 
 OR (SUBSTR (tp_tarifacao, 0, 6) = 'VC1FOI') OR  (SUBSTR(TP_TARIFACAO,0,3)='VCF') 
 OR (SUBSTR(TP_TARIFACAO,0,3)='VC3') OR (SUBSTR(TP_TARIFACAO,0,3)='VC2' 
 AND TO_NUMBER(NVL(CD_OPLD_B,'0')) NOT IN (88,89) ) ) AND SUBSTR(TRIM(MSISDN_B),0,1) <> 'A' 
 AND CD_OPLD  IN ('31', '88', '90')
 ----1232




-- Conforme  explicação do cabeçalho, abaixo segue as querys para verificação dos TIPOS .

---  TIPOS: 


------------------------- UNIVERSAL --------------------------
 
--- São todos os registros que possuem TP_TARICAO = 'VCF%'  ou 'VC%F%'
--- Devido pertencer ao um tipo de arquivo TLM possuem as operadoras : 31,88,90 

-- TODOS OS REGISTROS UNIVERSAL 
SELECT ROWID, a.*  FROM CHAMADA a --_BACKUP_ANTES_200431 a   -- CHAMADA 
WHERE  CD_OPLD IN ('88' , '90', '31') 
AND (  SUBSTR(TP_TARIFACAO, 1,5) = 'VC1FM'
OR  SUBSTR(TP_TARIFACAO, 1,5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC1FOI'
OR  SUBSTR(TP_TARIFACAO,1,5) =   'VC2FF' 
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC2FOI'
OR  SUBSTR(TP_TARIFACAO, 1, 5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =   'VC3FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =    'VC3FM'
OR  SUBSTR(TP_TARIFACAO , 1,6) =   'VC3FOI'
OR  SUBSTR(TP_TARIFACAO , 1,4) =   'LDIF' )  
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
--AND msisdn = '558222002882'
-- total : 635



--- registros com ERRO
--- No caso dos registro Universal os registros com valor negativo  NÃO vão para arquivo erro.
SELECT  ROWID, A.*   FROM CHAMADA  A  --  _BACKUP_ANTES_200431 A-- CHAMADA
WHERE  CD_OPLD IN ('88' , '90', '31') 
AND (  SUBSTR(TP_TARIFACAO, 1,5) = 'VC1FM'
OR  SUBSTR(TP_TARIFACAO, 1,5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC1FOI'
OR  SUBSTR(TP_TARIFACAO,1,5) =   'VC2FF' 
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC2FOI'
OR  SUBSTR(TP_TARIFACAO, 1, 5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =   'VC3FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =    'VC3FM'
OR  SUBSTR(TP_TARIFACAO , 1,6) =   'VC3FOI'
OR  SUBSTR(TP_TARIFACAO , 1,4) =   'LDIF' )  
AND ( INSTR(VL_CHAMADA , '.') = 1
OR INSTR(VL_CHAMADA , ',' ) =1 )
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
-- total : 0 

 



--- registros REJEITADOS
SELECT *  FROM  CHAMADA --_BACKUP_ANTES_200431  --CHAMADA
WHERE  CD_OPLD IN ('88' , '90', '31') 
AND (  SUBSTR(TP_TARIFACAO, 1,5) = 'VC1FM'
OR  SUBSTR(TP_TARIFACAO, 1,5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC1FOI'
OR  SUBSTR(TP_TARIFACAO,1,5) =   'VC2FF' 
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC2FOI'
OR  SUBSTR(TP_TARIFACAO, 1, 5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =   'VC3FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =    'VC3FM'
OR  SUBSTR(TP_TARIFACAO , 1,6) =   'VC3FOI'
OR  SUBSTR(TP_TARIFACAO , 1,4) =   'LDIF' )  
AND  (VL_CHAMADA  < 0 
OR  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
 -- total : 41
 
 

-- registros OK
SELECT * FROM CHAMADA --_BACKUP_ANTES_200431 --CHAMADA 
WHERE  CD_OPLD IN ('88' , '90', '31') 
AND (  SUBSTR(TP_TARIFACAO, 1,5) = 'VC1FM'
OR  SUBSTR(TP_TARIFACAO, 1,5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC1FOI'
OR  SUBSTR(TP_TARIFACAO,1,5) =   'VC2FF' 
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC2FOI'
OR  SUBSTR(TP_TARIFACAO, 1, 5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =   'VC3FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =    'VC3FM'
OR  SUBSTR(TP_TARIFACAO , 1,6) =   'VC3FOI'
OR  SUBSTR(TP_TARIFACAO , 1,4) =   'LDIF' )  
AND  INSTR(VL_CHAMADA , '.') = 0
AND INSTR(VL_CHAMADA , ',' ) =0 
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
MINUS 
SELECT *  FROM  CHAMADA --_BACKUP_ANTES_200431  --CHAMADA
WHERE  CD_OPLD IN ('88' , '90', '31') 
AND (  SUBSTR(TP_TARIFACAO, 1,5) = 'VC1FM'
OR  SUBSTR(TP_TARIFACAO, 1,5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC1FOI'
OR  SUBSTR(TP_TARIFACAO,1,5) =   'VC2FF' 
OR  SUBSTR(TP_TARIFACAO, 1,6) = 'VC2FOI'
OR  SUBSTR(TP_TARIFACAO, 1, 5) =  'VC1FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =   'VC3FF'
OR  SUBSTR(TP_TARIFACAO, 1,5) =    'VC3FM'
OR  SUBSTR(TP_TARIFACAO , 1,6) =   'VC3FOI'
OR  SUBSTR(TP_TARIFACAO , 1,4) =   'LDIF' )  
AND  (VL_CHAMADA  < 0 
OR  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
-- total 338









----------------------- OUTORGAS ------------------------------

-- São todos os registros que possuem TP_TARIFACAO <> 'VCF%'  ou  TP_TARIFACAO <> 'VC%F%'
--- Devido pertencer ao um tipo de arquivo TLM possuem as operadoras : 31 ,88, 90 

--- TODOS REGISTROS OUTORGAS  ( regra 1 , ERRO, REJEITADO . OK )
--  TODOS REGISTROS   ( regra 1 ) 
SELECT ROWID,a.* FROM CHAMADA a ---_BACKUP_ANTES_200431 a
WHERE  SUBSTR ( TP_TARIFACAO , 1,3) = 'LDI'  
AND (SUBSTR ( TP_TARIFACAO , 1,3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
AND  CD_OPLD = '31'
AND SUBSTR (MSISDN , 1, 4) <> '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
--AND msisdn = '558122002881'
-- total : 369


-- registros ERRO  ( regra 1) 
SELECT *  FROM CHAMADA ---_BACKUP_ANTES_200431
WHERE  SUBSTR ( TP_TARIFACAO , 1,3) = 'LDI'  
AND (SUBSTR ( TP_TARIFACAO , 1,3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
AND  CD_OPLD = '31'
AND SUBSTR (MSISDN , 1, 4) <> '5534'
AND ( INSTR(VL_CHAMADA , '.') = 1
OR INSTR(VL_CHAMADA , ',' ) = 1
OR  INSTR(VL_CHAMADA , '-' ) = 1)
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
--AND msisdn = '558122002881'
--total : 31



-- registros REJEITADOS ( regra 1)
SELECT *  FROM CHAMADA  --a--_BACKUP_ANTES_200431 a
WHERE  SUBSTR ( TP_TARIFACAO , 1,3) = 'LDI'  
AND (SUBSTR ( TP_TARIFACAO , 1,3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
AND  CD_OPLD = '31'
AND SUBSTR (MSISDN , 1, 4) <> '5534'
AND  (  DURACAO < 0 
OR SUBSTR( MSISDN_B, 1,2) = '90'  
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
--AND msisdn = '558122002881'
--total : 14



-- registros OK  ( regra 1  )
SELECT * FROM CHAMADA ---_BACKUP_ANTES_200431
WHERE  SUBSTR ( TP_TARIFACAO , 1,3) = 'LDI'  
AND (SUBSTR ( TP_TARIFACAO , 1,3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
AND  CD_OPLD = '31'
AND SUBSTR (MSISDN , 1, 4) <> '5534'
AND  INSTR(VL_CHAMADA , '.') = 0
AND INSTR(VL_CHAMADA , ',' ) = 0
AND  INSTR(VL_CHAMADA , '-' ) = 0
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
MINUS 
SELECT * FROM CHAMADA  --_BACKUP_ANTES_200431
WHERE  SUBSTR ( TP_TARIFACAO , 1,3) = 'LDI'  
AND (SUBSTR ( TP_TARIFACAO , 1,3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
AND  CD_OPLD = '31'
AND SUBSTR (MSISDN , 1, 4) <> '5534'
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
-- total : 285



-- TODOS REGISTROS  ( regra 2)  
SELECT  *  FROM CHAMADA  --a--_BACKUP_ANTES_200431 a
WHERE  CD_OPLD IN ('31') 
AND  (SUBSTR(TP_TARIFACAO , 1, 3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
 AND (CD_ZONA_ORIGEM LIKE ( 'TM%_R')  OR CD_ZONA_ORIGEM  LIKE ('LC%_R'))
 AND ( TP_CHAMADA = 1) -- AND  (SUBSTR(TP_TARIFACAO, 1,3 ) = 'VC2' OR  SUBSTR(TP_TARIFACAO, 1,3 ) = 'VC3'))
AND SUBSTR(MSISDN, 1, 4) <> '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
-- total : 134

-- registros com ERRO  ( regra 2 ) 
SELECT * FROM CHAMADA --_BACKUP_ANTES_200431
WHERE  CD_OPLD = '31' 
AND  (SUBSTR(TP_TARIFACAO , 1, 3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
 AND (CD_ZONA_ORIGEM LIKE ( 'TM%_R')  OR CD_ZONA_ORIGEM  LIKE ('LC%_R'))
 AND ( TP_CHAMADA = 1) -- AND  (SUBSTR(TP_TARIFACAO, 1,3 ) = 'VC2' OR  SUBSTR(TP_TARIFACAO, 1,3 ) = 'VC3'))
AND SUBSTR(MSISDN, 1, 4) <> '5534'
AND ( INSTR(VL_CHAMADA , '.') = 1
OR INSTR(VL_CHAMADA , ',' ) = 1
OR  INSTR(VL_CHAMADA , '-' ) = 1)
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
--total: 3




-- registros REJEITADOS (  regra 2 )
SELECT *  FROM CHAMADA --_BACKUP_ANTES_200431
WHERE  CD_OPLD = '31' 
AND  (SUBSTR(TP_TARIFACAO , 1, 3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
 AND (CD_ZONA_ORIGEM LIKE ( 'TM%_R')  OR CD_ZONA_ORIGEM  LIKE ('LC%_R'))
 AND ( TP_CHAMADA = 1) 
AND SUBSTR(MSISDN, 1, 4) <> '5534'
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
--total: 18


-- registros OK  ( regra 2) 
SELECT *  FROM CHAMADA --_BACKUP_ANTES_200431
WHERE  CD_OPLD IN ('31') 
AND (SUBSTR(TP_TARIFACAO , 1, 3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
 AND (CD_ZONA_ORIGEM LIKE ( 'TM%_R')  OR CD_ZONA_ORIGEM  LIKE ('LC%_R'))
 AND ( TP_CHAMADA = 1) 
AND SUBSTR(MSISDN, 1, 4) <> '5534'
AND INSTR(VL_CHAMADA , '.') = 0
AND INSTR(VL_CHAMADA , ',' ) = 0
AND  INSTR(VL_CHAMADA , '-' ) = 0
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
MINUS 
SELECT *  FROM CHAMADA --_BACKUP_ANTES_200431
WHERE  CD_OPLD IN ('31') 
AND  (SUBSTR(TP_TARIFACAO , 1, 3) <> 'VCF'  OR  TP_TARIFACAO NOT LIKE ('VC%F%'))
 AND (CD_ZONA_ORIGEM LIKE ( 'TM%_R')  OR CD_ZONA_ORIGEM  LIKE ('LC%_R'))
 AND ( TP_CHAMADA = 1) 
AND SUBSTR(MSISDN, 1, 4) <> '5534'
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND msisdn = '558122002881'
-- total : 113 








-------------------------  NORMAL --------------------------------

-- São todos os registros que possuem TP_TARIFACAO <> 'VCF'


--TOTAL DE REGISTROS ( regra 1 )
SELECT  *  FROM CHAMADA --_BACKUP_ANTES_200431 
WHERE   CD_OPLD IN ('88' , '90') 
AND SUBSTR( MSISDN, 1,4) = '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
-- total : 261



--  NORMAL  ERRO ( regra 1 ) 
SELECT  *  FROM CHAMADA ---_BACKUP_ANTES_200431 
WHERE   CD_OPLD IN ('88' , '90') 
AND SUBSTR( MSISDN, 1,4) = '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND ( INSTR(VL_CHAMADA , '.') = 1
OR INSTR(VL_CHAMADA , ',' ) = 1
OR  INSTR(VL_CHAMADA , '-' ) = 1)
-- total : 10


-- NORMAL  REJEITADO ( regra 1) 
SELECT  *  FROM CHAMADA ---_BACKUP_ANTES_200431 
WHERE   CD_OPLD IN ('88' , '90') 
AND SUBSTR( MSISDN, 1,4) = '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
--TOTAL: 3


-- NORMAL OK ( regra 1 ) 
SELECT  *  FROM CHAMADA ---_BACKUP_ANTES_200431 
WHERE   CD_OPLD IN ('88' , '90') 
AND SUBSTR( MSISDN, 1,4) = '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND ( INSTR(VL_CHAMADA , '.') = 0
OR INSTR(VL_CHAMADA , ',' ) = 0
OR  INSTR(VL_CHAMADA , '-' ) = 0)
MINUS
SELECT  *  FROM CHAMADA ---_BACKUP_ANTES_200431 
WHERE   CD_OPLD IN ('88' , '90') 
AND SUBSTR( MSISDN, 1,4) = '5534'
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
--TOTAL: 258









-- TOTAL DE REGISTROS  (  regra 2 ) 
SELECT  COUNT( *) FROM CHAMADA  --_BACKUP_ANTES_200431 
WHERE   CD_OPLD  = '31'  
AND (CD_ZONA_ORIGEM LIKE ( 'OIAR34%')  OR CD_ZONA_ORIGEM  LIKE ('OIAR34_R'))
AND  SUBSTR(TP_TARIFACAO, 1,3) <> 'VCF'    --OR  TP_TARIFACAO NOT LIKE ('VC%F%')) -- LINHA A CONFIRMAR..
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
-- total : 139



-- NORMAL ERRO ( regra 2) 
SELECT  COUNT( *) FROM CHAMADA --_BACKUP_ANTES_200431 
WHERE   CD_OPLD  = '31'  
AND (CD_ZONA_ORIGEM LIKE ( 'OIAR34%')  OR CD_ZONA_ORIGEM  LIKE ('OIAR34_R'))
AND  SUBSTR(TP_TARIFACAO, 1,3) <> 'VCF'    --OR  TP_TARIFACAO NOT LIKE ('VC%F%')) -- LINHA A CONFIRMAR..
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND ( INSTR(VL_CHAMADA , '.') = 1
OR INSTR(VL_CHAMADA , ',' ) = 1
OR  INSTR(VL_CHAMADA , '-' ) = 1)
--total: 4



--- NORMAL REJEITADO ( regra 2) 
SELECT  COUNT( *) FROM CHAMADA --_BACKUP_ANTES_200431 
WHERE   CD_OPLD  = '31'  
AND (CD_ZONA_ORIGEM LIKE ( 'OIAR34%')  OR CD_ZONA_ORIGEM  LIKE ('OIAR34_R'))
AND  SUBSTR(TP_TARIFACAO, 1,3) <> 'VCF'    --OR  TP_TARIFACAO NOT LIKE ('VC%F%')) -- LINHA A CONFIRMAR..
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
-- TOTAL: 7


--- NORMAL OK ( regra  2) 
SELECT  *  FROM CHAMADA --_BACKUP_ANTES_200431 
WHERE   CD_OPLD  = '31'  
AND (CD_ZONA_ORIGEM LIKE ( 'OIAR34%')  OR CD_ZONA_ORIGEM  LIKE ('OIAR34_R'))
AND  SUBSTR(TP_TARIFACAO, 1,3) <> 'VCF'    --OR  TP_TARIFACAO NOT LIKE ('VC%F%')) -- LINHA A CONFIRMAR..
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND ( INSTR(VL_CHAMADA , '.') = 0
OR INSTR(VL_CHAMADA , ',' ) = 0
OR  INSTR(VL_CHAMADA , '-' ) = 0)
MINUS
SELECT  * FROM CHAMADA --_BACKUP_ANTES_200431 
WHERE   CD_OPLD  = '31'  
AND (CD_ZONA_ORIGEM LIKE ( 'OIAR34%')  OR CD_ZONA_ORIGEM  LIKE ('OIAR34_R'))
AND  SUBSTR(TP_TARIFACAO, 1,3) <> 'VCF'    --OR  TP_TARIFACAO NOT LIKE ('VC%F%')) -- LINHA A CONFIRMAR..
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
-- TOTAL: 58





-- TOTAL  DE REGISTROS (  regra 3)  
SELECT ROWID, A.*   FROM CHAMADA A 
WHERE   CD_OPLD =  '31' 
AND  (SUBSTR(TP_TARIFACAO, 1, 3) = 'VC2' OR  SUBSTR(TP_TARIFACAO,1,3) ='VC3')
AND  tp_tarifacao NOT IN ('VC%F%')
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
--total: 554



-- NORMAL ERRO ( regra 3) 
SELECT * FROM CHAMADA 
WHERE   CD_OPLD =  '31' 
AND  (SUBSTR(TP_TARIFACAO, 1, 3) = 'VC2' OR  SUBSTR(TP_TARIFACAO,1,3) ='VC3')
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  tp_tarifacao NOT IN ('VC%F%')
AND ( INSTR(VL_CHAMADA , '.') = 1
OR INSTR(VL_CHAMADA , ',' ) = 1
OR  INSTR(VL_CHAMADA , '-' ) = 1)
-- TOTAL: 3


-- NORMAL REJEITADO ( rgera 3 )
SELECT *  FROM CHAMADA 
WHERE   CD_OPLD =  '31' 
AND  (SUBSTR(TP_TARIFACAO, 1, 3) = 'VC2' OR  SUBSTR(TP_TARIFACAO,1,3) ='VC3')
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  tp_tarifacao NOT IN ('VC%F%')
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
-- TOTAL : 37


-- NORMAL OK  ( regra 3 )
SELECT *  FROM CHAMADA 
WHERE   CD_OPLD =  '31' 
AND  (SUBSTR(TP_TARIFACAO, 1, 3) = 'VC2' OR  SUBSTR(TP_TARIFACAO,1,3) ='VC3')
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND ( INSTR(VL_CHAMADA , '.') = 0
OR INSTR(VL_CHAMADA , ',' ) = 0
OR  INSTR(VL_CHAMADA , '-' ) = 0)
AND  tp_tarifacao NOT IN ('VC%F%')
MINUS
SELECT *  FROM CHAMADA 
WHERE   CD_OPLD =  '31' 
AND  (SUBSTR(TP_TARIFACAO, 1, 3) = 'VC2' OR  SUBSTR(TP_TARIFACAO,1,3) ='VC3')
AND   DT_INICIO > (TO_DATE('05/01/2007 11:59:59' , 'DD/MM/YYYY HH24:MI:SS')) 
AND DT_INICIO <  (SYSDATE-2)
AND  tp_tarifacao NOT IN ('VC%F%')
AND  (  DURACAO < 0
OR SUBSTR( MSISDN_B, 1,2) = '90'
OR (VL_CHAMADA = 0 AND TP_CHAMADA <> 3)
OR ( VL_CHAMADA > 0 AND DURACAO = 0)
OR (VL_CHAMADA = 0    AND OPERADORA = 'Oi' AND  SUBSTR( TP_TARIFACAO , 1,3 ) = 'VC3')
OR (CD_OPLD = 0)
OR (DURACAO = 0 AND VL_CHAMADA IS NULL))
-- TOTAL: 260


















































